@server = http://localhost:57741
@auth = Authorization: Basic alice:


### BusinessPartners
# @name BusinessPartners_GET
GET {{server}}/odata/v4/nebula/BusinessPartners?$expand=contatos
{{auth}}


### BusinessPartners
# @name BusinessPartners_POST
POST {{server}}/odata/v4/nebula/BusinessPartners
Content-Type: application/json
{{auth}}

{
  "razaoSocial": "razaoSocial-343396",
  "codigoBpSap": "codigoBpSap-343396",
  "numeroInscricao": "numeroInscricao-343396",
  "identificacao": "identificacao-343396",
  "email": "email-343396",
  "statusNebula": "statusNebula-343396",
  "tipoCadastro": "tipoCadastro-343396",
  "createdAt": "2012-09-13T02:00:00.000Z",
  "createdBy": "createdBy.7cys@example.org",
  "modifiedAt": "2011-09-19T02:00:00.000Z",
  "modifiedBy": "modifiedBy.7cys@example.org"
}


### BusinessPartners
# @name BusinessPartners_PATCH
PATCH {{server}}/odata/v4/nebula/BusinessPartners/343396af-b1d9-4dcc-a197-73bf1a725a03
Content-Type: application/json
{{auth}}

{
  "ID": "343396af-b1d9-4dcc-a197-73bf1a725a03",
  "razaoSocial": "razaoSocial-343396",
  "codigoBpSap": "codigoBpSap-343396",
  "numeroInscricao": "numeroInscricao-343396",
  "identificacao": "identificacao-343396",
  "email": "email-343396",
  "statusNebula": "statusNebula-343396",
  "tipoCadastro": "tipoCadastro-343396",
  "createdAt": "2012-09-13T02:00:00.000Z",
  "createdBy": "createdBy.7cys@example.org",
  "modifiedAt": "2011-09-19T02:00:00.000Z",
  "modifiedBy": "modifiedBy.7cys@example.org"
}


### BusinessPartners
# @name BusinessPartners_DELETE
DELETE {{server}}/odata/v4/nebula/BusinessPartners/343396af-b1d9-4dcc-a197-73bf1a725a03
Content-Type: application/json
{{auth}}